source 'http://rubygems.org/'

gem 'rails', '2.3.4'

gem 'i18n'
gem 'aws-s3'
gem 'ruby-hmac'
gem 'ruby-mp3info'
gem 'will_paginate'
gem 'bteitelb-paperclip'
gem 'right_aws'
gem 'authlogic'
gem 'discogs'
gem 'scrobbler'
gem 'scrobbler2'
gem 'activemerchant'
gem 'MP4Info'
gem 'bluecloth'
gem 'rbrainz'
gem 'memcache-auth'
gem 'rfeedfinder'
gem 'feed-normalizer'
gem 'scoped_search'
